name: BOOT
on:
  watch:
    types: [started]
    
#  push:
#    branches: 
#      - master
  
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Run boot script
      run: |
        ./autoexec.sh
        
#     - uses: actions/checkout@v1
#     - name: Setup tmate session
#       uses: mxschmitt/action-tmate@v1
