name: BOOT
on:
  watch:
    types: [started]
    
#  push:
#    branches: 
#      - master
  
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Run boot script
      run: |
        ./autoexec.sh
